### ISSUE TITLE
Release request for #3211

### ISSUE THREAD

**Issue by OTL** [sebcrozet/kiss3d#323]
I want to try the new vertex to support more complicated meshes.

https://github.com/sebcrozet/kiss3d/pull/321

If the situation is stable, is it possible to release the new version?

**Comment by virtualritz** [comment]
In the meantime, you can use an overlay:

```toml
[patch.crates-io]
kiss3d = { git = "https://github.com/sebcrozet/kiss3d.git", branch = "master" }
```
